apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache2-deployment
  template:
    metadata:
      labels:
        app: apache2-deployment
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: apache2
        image: santu1120/container:v1
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 80
          name: apache2
---
apiVersion: v1
kind: Service
metadata:
  name: apache2-deployment
spec:
  ports:
  - port: 80
  selector:
    app: apache2-deployment
