apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache2-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apache2-deployment
  template:
    metadata:
      labels:
        app: apache2-deployment
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: apache2-deployment
        image: santu1120/container:v1
        ports:
        - containerPort: 80
          name: apache2
---
apiVersion: v1
kind: Service
metadata:
  name: apache2-deployment
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: apache2-deployment
