apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apache2
  template:
    metadata:
      labels:
        app: apache2
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: apache2
        image: santu1234.azurecr.io/container:v1
        command: ["sh","-c","tail -f /dev/null","service"]
        args: ["apache2" "start"]
        ports:
        - containerPort: 80
          name: apache2
---
apiVersion: v1
kind: Service
metadata:
  name: apache2
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: apache2
